version: '3.8'

services:
  # Development environment
  angular-dev:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "4200:4200"
    command: >
      bash -c "npm install && 
              npm start -- --host 0.0.0.0 --disable-host-check"
    environment:
      - NODE_ENV=development

  # Production build
  angular-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped 