name: All Checks

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  verify:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    # Code Quality
    - name: Check formatting with Prettier
      run: npx prettier --check "src/**/*.{ts,html,css,scss}"
    
    - name: Run ESLint
      run: npx ng lint
    
    # Build
    - name: Build
      run: npm run build
    
    # Unit Tests
    - name: Run unit tests
      run: npm run test:coverage
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./coverage/angular-app/
        fail_ci_if_error: false
    
    # E2E Tests
    - name: Cypress run
      uses: cypress-io/github-action@v5
      with:
        start: npm start
        wait-on: 'http://localhost:4200'
        browser: chrome
        headless: true
    
    # Final report
    - name: Comment on PR
      if: github.event_name == 'pull_request' && success()
      uses: actions/github-script@v6
      with:
        script: |
          const badge = '[![All Checks](https://img.shields.io/badge/all%20checks-passing-brightgreen)](https://github.com/${{ github.repository }}/actions/workflows/all-checks.yml)';
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `## All Checks Passed ✅\n\n${badge}\n\nCode quality, build, unit tests, and E2E tests are all passing.`
          }) 