name: "All Checks"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
      - name: Run tests
        run: npm run test:ci
      - name: Run coverage tests
        run: npm run test:coverage
      - name: Run E2E tests
        run: npm run e2e:ci
      - name: Run accessibility checks
        run: npm run lint:a11y
      - name: Run code quality checks
        run: npm run lint && npm run format:check
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Create PR comment
        if: github.event_name == 'pull_request'
        run: |
          echo "## Build Status" > comment.md
          echo "- Build: ✅ Passed" >> comment.md
          echo "- Tests: ✅ Passed" >> comment.md
          echo "- Coverage: ✅ Passed" >> comment.md
          echo "- E2E: ✅ Passed" >> comment.md
          echo "- Accessibility: ✅ Passed" >> comment.md
          echo "- Code Quality: ✅ Passed" >> comment.md
          gh pr comment ${{ github.event.pull_request.number }} --body-file comment.md 