name: All Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  all-checks:
    runs-on: ubuntu-latest
    
    # Add timeout to prevent hanging jobs
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
      # Retry chrome installation if it fails
      continue-on-error: true
      id: chrome-install

    - name: Retry Chrome Install
      if: steps.chrome-install.outcome == 'failure'
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Clean npm cache and node_modules
      run: |
        rm -rf node_modules
        rm -rf package-lock.json
        npm cache clean --force

    - name: Install dependencies
      run: |
        npm install
        npm ci
      
    - name: Nx Cache
      uses: actions/cache@v3
      with:
        path: .nx/cache
        key: ${{ runner.os }}-nx-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nx-

    - name: Build
      run: npx nx build angular-app --configuration=production
      # Capture build errors in artifacts
      continue-on-error: true
      id: build

    - name: Upload Build Logs
      if: steps.build.outcome == 'failure'
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          dist
          .nx/cache/logs
        
    - name: Lint
      run: npx nx lint angular-app
      
    - name: Accessibility checks
      run: npm run lint:a11y
      # Upload a11y report even if check fails
      id: a11y
      continue-on-error: true

    - name: Upload A11y Report
      if: always() && steps.a11y.outcome == 'failure'
      uses: actions/upload-artifact@v4
      with:
        name: accessibility-report
        path: .eslintrc.json
      
    - name: Check formatting
      run: npm run format:check
      
    - name: Run unit tests
      run: npx nx test angular-app --configuration=ci --browsers=ChromeHeadless --watch=false
      env:
        CHROME_BIN: chrome
      # Upload test results even if tests fail
      id: unit-tests
      continue-on-error: true

    - name: Upload Test Coverage
      if: always()  # Upload even if tests fail
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage

    - name: Run e2e tests
      run: npx nx e2e angular-app --configuration=production --browser=chrome --headless
      env:
        CHROME_BIN: chrome
      id: e2e-tests
      continue-on-error: true

    - name: Upload E2E Artifacts
      if: failure()  # Only upload if E2E tests fail
      uses: actions/upload-artifact@v4
      with:
        name: cypress-artifacts
        path: |
          cypress/videos
          cypress/screenshots

    - name: Upload Build Artifacts
      if: failure()  # Only upload if build fails
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: dist

    # Final status check
    - name: Check for failures
      if: always()
      run: |
        if [ "${{ steps.build.outcome }}" == "failure" ] || \
           [ "${{ steps.a11y.outcome }}" == "failure" ] || \
           [ "${{ steps.unit-tests.outcome }}" == "failure" ] || \
           [ "${{ steps.e2e-tests.outcome }}" == "failure" ]; then
          echo "One or more checks failed"
          exit 1
        fi
